#!/usr/bin/env python3
import sys, json
import bversion.server as server
from bversion.http.http_server import HTTPServer
from bversion.common import file_get_contents

#===============================================================================
conf_path = '/etc/bversion/server.json'
if len(sys.argv) > 1 and sys.argv[1] == '-c':
    conf_path = sys.argv[2]

server.init_server(json.loads(file_get_contents(conf_path)))

#===============================================================================
listen      = ''
listen_port = 8090

if 'listen' in server.config:
    listen = server.config['listen']

if 'listen_port' in server.config:
    listen_port = server.config['listen_port']


# ------------------------------
if __name__ == "__main__":
    HTTPServer(listen, listen_port, server.endpoint)

