#!/usr/bin/env python3
import sys, json
from shttpfs3 import repo_manager
from shttpfs3.common import file_get_contents

#===============================================================================
conf_path = '/etc/shttpfs/server.json'
if len(sys.argv) > 1 and sys.argv[1] == '-c':
    conf_path = sys.argv[2]

repo_manager.init(json.loads(file_get_contents(conf_path)))

#===============================================================================
repo_manager.run()
