#!/usr/bin/env python3

# varify
# read and validate the entire repo

# backup

# Start backup process

# Store the repo on S3 'as is'

# Store a dir containing objects whose hashes match those of the versions

# Using this and file listing on remote, we can check which versions have been uploaded

# For every version starting at the oldest
    # Get a list of objects in that version
    # Get a list of objects on the remote
    # Diff the two
    # Upload anything that does not already exist


# This process can be done incrementally, and interupted without issue.
and upload needed 