#!/usr/bin/env python
import sys, json
from shttpfs.common import file_get_contents, file_put_contents

args = list(sys.argv)[1:]

source                = args[0]
destination           = args[1]
current_revision_hash = args[2]

manifest = json.loads(file_get_contents(source))

new_manifest = {'format_version' : 2,
                'root'           : manifest['root'],
                'have_revision'  : current_revision_hash,
                'files'          : {fle['path'] : fle for fle in manifest['files']}}

file_put_contents(destination, json.dumps(new_manifest))
