#!/usr/bin/env python
import sys, json
import shttpfs.server_2 as server
from   shttpfs.common import file_get_contents
import bjoern

#===============================================================================
conf_path = '/etc/shttpfs/server.json'
if len(sys.argv) > 1 and sys.argv[1] == '-c':
    conf_path = sys.argv[2]
server.config = json.loads(file_get_contents(conf_path))

#===============================================================================
bjoern.run(server.wsgi_application, '0.0.0.0', 8070)

