#!/usr/bin/env python3
import sys, json
import shttpfs3.server as server
from shttpfs3.http_server import HTTPServer
from shttpfs3.common import file_get_contents

#===============================================================================
conf_path = '/etc/shttpfs/server.json'
if len(sys.argv) > 1 and sys.argv[1] == '-c':
    conf_path = sys.argv[2]
server.config = json.loads(file_get_contents(conf_path))

#===============================================================================
if __name__ == "__main__":
    HTTPServer('0.0.0.0', 8090, server.endpoint)

